olist_customers_dataset: D:/Users/Verner/Documents/cours/major/datascience/projet fil rouge/data/olist_customers_dataset.csv
olist_geolocation_dataset: D:/Users/Verner/Documents/cours/major/datascience/projet fil rouge/data/olist_geolocation_dataset.csv
olist_order_items_dataset: D:/Users/Verner/Documents/cours/major/datascience/projet fil rouge/data/olist_order_items_dataset.csv
olist_order_payments_dataset: D:/Users/Verner/Documents/cours/major/datascience/projet fil rouge/data/olist_order_payments_dataset.csv
olist_order_reviews_dataset: D:/Users/Verner/Documents/cours/major/datascience/projet fil rouge/data/olist_order_reviews_dataset.csv
olist_orders_dataset: D:/Users/Verner/Documents/cours/major/datascience/projet fil rouge/data/olist_orders_dataset.csv
olist_products_dataset: D:/Users/Verner/Documents/cours/major/datascience/projet fil rouge/data/olist_products_dataset.csv
olist_sellers_dataset: D:/Users/Verner/Documents/cours/major/datascience/projet fil rouge/data/olist_sellers_dataset.csv
product_category_name_translation: D:/Users/Verner/Documents/cours/major/datascience/projet fil rouge/data/product_category_name_translation.csv
